name: Test

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  test:
    name: 'Build and test'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create micromamba environment
        uses: mamba-org/setup-micromamba@v2
        with:
          environment-file: dev-environment.yml
          init-shell: >-
            bash

      - name: Debug
        run: |
          micromamba list
          which meson

      - name: Build
        run: |
          meson setup build
          cd build
          meson compile

      - name: Smoke test
        working-directory: build
        run: |
          ./git2cpp -v
          ./git2cpp -h

      - name: Run tests
        run: |
          pytest -v
